# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-08 11:23
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情'),
        ),
    ]
