"""empty message

Revision ID: 24c2c23964d0
Revises: 563024a64fe8
Create Date: 2018-09-07 10:36:37.568000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c2c23964d0'
down_revision = '563024a64fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_author', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tbl_book', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_book', 'create_time')
    op.drop_column('tbl_author', 'create_time')
    # ### end Alembic commands ###
