"""empty message

Revision ID: 563024a64fe8
Revises: 076cf30cc1f2
Create Date: 2018-09-07 10:14:54.326000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563024a64fe8'
down_revision = '076cf30cc1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='tbl_author')
    op.drop_index('name', table_name='tbl_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'tbl_book', ['name'], unique=True)
    op.create_index('name', 'tbl_author', ['name'], unique=True)
    # ### end Alembic commands ###
